### ISSUE TITLE
Low performance while generating millions of utterances

### ISSUE THREAD

**Issue by rekire** [KayLerch/alexa-utterance-generator#1]
I noticed that the performance get very low when you generate a lot of permutations. The issue is that you validate every new sentence with every generated so far.

The performance issue is located in [`UtteranceGenerator.store()`](https://github.com/KayLerch/alexa-utterance-generator/blob/3adc669e6c1e6d6b7248aff2cb76fc76f0f628fc/src/main/java/io/klerch/alexa/utterances/UtteranceGenerator.java#L139-L156). For my usage I removed the check and added a post processing check.

Please consider to move the check out of the storage.

**Comment by KayLerch** [comment]
Sounds reasonable :)
I did never stress this tool like you did. I agree this needs an improvement even though it is not very relevant for the use case of Alexa skills. Interaction model size is limited and won´t store millions of utterances. The most I`ve seen so far was about 15k utterances.

**Comment by KayLerch** [comment]
Hi Rekire,

with the new version 2 of the generator I paid more attention to runtime performance. Even though I followed your suggestion and now do validation and double detection at the very end of the process it still takes ages to process millions of utterances. I am sorry. I tried to improve the detection logic but seems like there is still room for improvement. If you want to give it a try, here it goes: https://github.com/KayLerch/alexa-utterance-generator/blob/master/src/main/java/io/klerch/alexa/utterances/model/InteractionModel.java#L110

What you can do now is to disable validation in the generator before calling generate(). This is the only booster I can offer right now ;)

**Comment by KayLerch** [comment]
Closing this for now. Suggestion given above. Anyone feel free to improve the algorithm referenced above as well.
