### ISSUE TITLE
Wrong detection of slot type alternatives

### ISSUE THREAD

**Issue by rekire** [KayLerch/alexa-utterance-generator#2]
I have a sample utterances like:

>I own a {{cat}|{dog}|{bird}|{fish}} with the name {search_term}

(While cat, dog, bird and fish are slot types for animal breeds)

The parser cannot handle the "{{" correctly [(jump to code)](https://github.com/KayLerch/alexa-utterance-generator/blob/3adc669e6c1e6d6b7248aff2cb76fc76f0f628fc/src/main/java/io/klerch/alexa/utterances/UtteranceGenerator.java#L97), since this is something which is impossible to parse with a regular expression (like regex and html).

Check also this online example where you can see that it is not correctly parsed: https://regex101.com/r/YdvLPX/1

The solution would be to parse the utterance and count the brackets, this would be also very helpful to detect typos like the wrong type of bracket { vs [ vs (

**Comment by KayLerch** [comment]
Nesting slots in alternative phrasing is currently not supported. However, I agree this would be a nice feature and I will consider adding it once I got the time for it. Feel free to send PR if you are not willing to wait for me :)

**Comment by rekire** [comment]
This would require a lot of changes to make that work. I started something very similar from scratch with the ability to maintain even 186,000,000 permutations per utterance. (I don't say that his makes sense. My 16GB json file for that single utterance is just crazy)

Here is my code for parsing in Kotlin:

        // Parse the line to make sure that there is no syntax error. Regex would not work for cases like {{Foo}|{Bar}}
        var start = 0
        var counter = 0
        val slots = mutableListOf<String>()
        var lastWasMasked = false
        line.forEachIndexed { i, c ->
            when (c) {
                '\\' -> lastWasMasked = true
                '{' -> {
                    if (!lastWasMasked) {
                        when (counter) {
                            0 -> start = i
                            1 -> {
                                // we found a slot type, that is fine
                            }
                            else -> throw ParseException("This line has a syntax error: $line", i)
                        }
                        counter++
                    }
                    lastWasMasked = false
                }
                '}' -> {
                    if (!lastWasMasked) {
                        when (counter) {
                            1 -> {
                                // we found the end of the slot
                                slots.add(line.substring(start, i + 1))
                            }
                            2 -> {
                                // we found the end of a slot type, that is fine
                            }
                            else -> throw ParseException("This line has a syntax error: $line", i)
                        }
                        counter--
                    }
                    lastWasMasked = false
                }
                else -> lastWasMasked = false
            }
        }
        if (counter != 0) throw ParseException("This line has a syntax error: $line", line.length)

**Comment by KayLerch** [comment]
I shipped some improvements the past few days and what you were looking for should now be available.

Check out:
https://github.com/KayLerch/alexa-utterance-generator#327-alternate-slots-

**Comment by KayLerch** [comment]
Resolved. Feature is now available.
