### ISSUE TITLE
Allow explicit names for slots

### ISSUE THREAD

**Issue by ansman** [KayLerch/alexa-utterance-generator#5]
Currently the slot name is generated from the slot type. It should be possible to define a custom name for the slot name.

Suggestions
---
```
MyIntent: I want to travel to {{city=AMAZON.US_CITY}}
```
```
MyIntent: I want to travel to {{city<AMAZON.US_CITY>}}
```
```
MyIntent: I want to travel to {{city[AMAZON.US_CITY]}}
```

**Comment by KayLerch** [comment]
Now there is. The syntax is as follows

`MyIntent: I want to travel to {{city:AMAZON.US_CITY}}`

Learn more about it here: https://github.com/KayLerch/alexa-utterance-generator#326-named-slots-

**Comment by ansman** [comment]
Great, thanks!
