### ISSUE TITLE
Add usage info to the README

### ISSUE THREAD

**Issue by ansman** [KayLerch/alexa-utterance-generator#6]
It seems this library is not published to maven central or any other major repository which leads to the conclusion that you should clone this library and compile it yourself, is that correct?

**Comment by KayLerch** [comment]
Correct. I made it more clear in the updated docs that this tool is meant to use in the IDE. 
I would really love to provide a better interface and even integration to other projects and Maven central. Let´s see what comes next :)
Thanks for the feedback anyway.

**Comment by KayLerch** [comment]
Hi Ansman,

I entirely refactored the code and also added new features to the generator. It is now also available in maven central: https://search.maven.org/artifact/io.klerch/alexa.utterances/2.0.0/jar

In your project, you need to initialize _Generator_ and call _generate()_ method. Either give it some file references to e.g. your *.grammar file or feed the generate() method with a list of strings containing the grammar specification line by line. Take https://github.com/KayLerch/alexa-utterance-generator/blob/master/src/main/java/io/klerch/alexa/utterances/UtteranceGenerator.java as a reference.

**Comment by ansman** [comment]
Great, nice work!
